{"name": "Verify User is able to Login with Valid Credentials", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\mohit.singla1\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\mohit.singla1\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login_steps.py\", line 22, in step_impl\n    assert result==True\n"}, "steps": [{"name": "Given I navigate to the login page", "status": "passed", "start": 1589730552233, "stop": 1589730556567}, {"name": "When I enter the username \"test@email.com\" and password \"abcabc\"", "status": "passed", "start": 1589730556568, "stop": 1589730578463}, {"name": "Then I am able to login", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\mohit.singla1\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\mohit.singla1\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login_steps.py\", line 22, in step_impl\n    assert result==True\n"}, "attachments": [{"name": "screenshot", "source": "15ab14a9-bf9f-43c0-99ae-56e1b8d42f76-attachment.png", "type": "image/png"}], "start": 1589730578464, "stop": 1589730600876}], "start": 1589730552228, "stop": 1589730600878, "uuid": "d7106f96-0096-4968-9871-d3f198d7ed5c", "historyId": "91448b54bb3daf54e5ac8751f2c2611e", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}